spring:
  datasource:
    jdbc.drive: com.mysql.cj.jdbc.Driver
    username: root
    password: qaz123456
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
  jpa:
      show-sql: true
#返回前端不显示null字段
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
weixin:
  appId: wx5271c0fec72093db
  secretId: 246690309fedaf15eb62ac16ce12bae9
  mchId: 1509922941
  mchKey: xinqushikejiyouxiangongsi6666666
  keyPath: C:\Users\26725\Desktop\learn\cert\apiclient_cert.p12
  notifyUrl: http://zhangql.natapp1.cc/sell/pay/notify
